### ISSUE TITLE
Special characters in novel name causing directory name error

### ISSUE THREAD

**Issue by BigBert101** [dr-nyt/Translated-Novel-Downloader#8]
This should be fixable by just adding a custom file name choice

**Comment by dr-nyt** [comment]
I had fixed this issue in a previous build, but later down the line somehow lost it. It is already fixed in the upcoming 0.7.2 version which should be out today or tomorrow. 

Anyhow thank you for bringing this up and support for adding custom file names and more will be added in future builds as advanced options.

I'll close this issue for now.

**Comment by dr-nyt** [comment]
@BigBert101 just a quick question, some people seem to have issues when running NovelScraper-0.7.1.exe. The usual problem is that the app won't launch or it takes about 5 minutes to appear. I'm assuming you don't have any of these issues. 

I'm currently waiting on confirmation for "app not opening" issue to be resolved and after that 0.7.2 should be released with support for m.wuxiaworld.co website aswell.

**Comment by dr-nyt** [comment]
@BigBert101 Version 0.7.2 is officially released and I'm pretty sure your problem is fixed. 
https://github.com/dr-nyt/Translated-Novel-Downloader/releases

In case it isn't then you can still reply here and I'll reopen the issue.
