### ISSUE TITLE
[Suggestion] m.wuxiaworld.co novels space between paragraphs

### ISSUE THREAD

**Issue by Jade-mist** [dr-nyt/Translated-Novel-Downloader#9]
Hey,
This is not an issue, but a suggestion. I don't know where to post suggestions, so if there is a special place for that please let me know.

What I like most about this tool is that the space between the paragraphs is not a full line, but rather just a little gap. I know the tool for m.wuxiaworld.co is done by webdagger, so it's not the same. I would like to suggest, if possible, to make the space between the paragraphs less, so it's easier to read.

I know this may seem like nitpicking, but is in fact very important for me. The big space makes the text seem choppy, glued together. Here is an example:
![image](https://user-images.githubusercontent.com/50962756/59008845-36c3f680-8834-11e9-9db6-eb7c35ac9bcf.png)

![image](https://user-images.githubusercontent.com/50962756/59008899-62df7780-8834-11e9-956c-c107c981543d.png)

Thank you for your time.

**Comment by dr-nyt** [comment]
We have made a discord channel so you can join that if you like and we will be posting our road map soon aswell: https://discord.gg/xD8Vtp

I think your problem is not because of how @webdagger made the code but because how m.wuxiaworld.co wrote their html, some novels have more spacing than others. But i believe there r still ways to fix this and @webdagger made a suggestion last night to make a better css for the files. You can expect this feature in the next version hopefully ;3

Oh and where do you mainly read your novels and what app do you use. Because I read on my phone using an app called moon+ reader and it allows you to change font sizes, spacing options and alot more. Its very powerful.

Our ultimate goal is to make an android app that automatically checks for new updates and notifys users directly and also allows reading directly in-app while giving user alot of freedom with formatting.

I'll tag this issue with enhancement and leave it open for now. We welcome feature requests like these because it brings fresh ideas to the table :)

Kind Regards,
dr_nyt.

**Comment by webdagger** [comment]
This has been fixed in version 0.74 by dr-nyt
